--The AQL (Analytical Query Language) is a domain-specific language used to query databases in the IBM Security QRadar SIEM (Security Information and Event Management) system.

--The queries you provided are selecting data from different tables in the ICON_EU_DB.RAW database schema that store information related to security events and logs generated by different Cisco security products, such as AMP (Advanced Malware Protection), ASA (Adaptive Security Appliance), FTD (Firepower Threat Defense), and Umbrella DNS.

--Each query is retrieving the first ten rows of data from the specified table, using the "Limit 10" clause. This allows the user to quickly preview the data and check for any potential issues or anomalies. These queries may be used for various purposes such as monitoring and investigating security incidents, analyzing network traffic, or generating reports.

SELECT *
FROM ICON_EU_DB.RAW.CISCO_AMP_EVENTS
Limit 10

SELECT *
FROM ICON_EU_DB.RAW.CISCO_ASA_FIREWALL
Limit 10

SELECT *
FROM ICON_EU_DB.RAW.CISCO_FTD_FIREWALL
Limit 10

SELECT *
FROM ICON_EU_DB.RAW.CISCO_FTD_IMPACT_FLAG_LOGS
Limit 10

SELECT *
FROM ICON_EU_DB.RAW.CISCO_UMBRELLA_DNS_LOGS
Limit 10

---------------------------------------------------------------------------------------------------------

--Top denied external IP addresses: 

-- This query selects the external IP and count of DNS queries that were blocked by Cisco Umbrella
SELECT EXTERNAL_IP, COUNT(*) AS count

-- This specifies the table to retrieve data from
FROM ICON_EU_DB.RAW.CISCO_UMBRELLA_DNS_LOGS

-- This limits the results to only those with action = 'BLOCKED'
WHERE action = 'BLOCKED'

-- This groups the results by external IP, so that the count is aggregated for each unique IP
GROUP BY EXTERNAL_IP

-- This orders the results in descending order based on the count of DNS queries, to find the IPs with the highest counts
ORDER BY count DESC

-- This limits the results to the top 10 entries
LIMIT 10;

--This query retrieves the top 10 external IPs with the highest count of DNS queries that were blocked by Cisco Umbrella, from the ICON_EU_DB.RAW.CISCO_UMBRELLA_DNS_LOGS table.





