---Alter Time zone
ALTER SESSION SET TIMEZONE = 'UTC';

--Office365 Audit Logs
SELECT User_ID, CLIENT_IP, OPERATION, EVENT_TIME
FROM ICON_EU_DB.RAW.O365_AUDIT_LOGS
WHERE User_ID LIKE '%@iconplc.com'
  AND OPERATION = 'UserLoggedIn'
  AND EVENT_TIME >= DATEADD(hour, -24, GETDATE())
ORDER BY EVENT_TIME DESC;

