-- Selects the first 10 rows from the MIMECAST_ATTACHMENT_PROTECT_LOGS table in the SECNNET_ASIA_JAPAN.RAW schema
SELECT *
FROM SECNNET_ASIA_JAPAN.RAW.MIMECAST_ATTACHMENT_PROTECT_LOGS
Limit 10

-- Selects the first 10 rows from the MIMECAST_AV_LOGS table in the SECNNET_ASIA_JAPAN.RAW schema
SELECT *
FROM SECNNET_ASIA_JAPAN.RAW.MIMECAST_AV_LOGS
Limit 10

-- Selects the first 10 rows from the MIMECAST_DELIVERY_LOGS table in the SECNNET_ASIA_JAPAN.RAW schema
SELECT *
FROM SECNNET_ASIA_JAPAN.RAW.MIMECAST_DELIVERY_LOGS
Limit 10

-- Selects the first 10 rows from the MIMECAST_IMPERSONATION_PROTECT_LOGS table in the SECNNET_ASIA_JAPAN.RAW schema
SELECT *
FROM SECNNET_ASIA_JAPAN.RAW.MIMECAST_IMPERSONATION_PROTECT_LOGS
Limit 10

-- Selects the first 10 rows from the MIMECAST_INTERNAL_EMAIL_PROTECT_LOGS table in the SECNNET_ASIA_JAPAN.RAW schema
SELECT *
FROM SECNNET_ASIA_JAPAN.RAW.MIMECAST_INTERNAL_EMAIL_PROTECT_LOGS
Limit 10

-- Selects the first 10 rows from the MIMECAST_PROCESS_LOGS table in the SECNNET_ASIA_JAPAN.RAW schema
SELECT *
FROM SECNNET_ASIA_JAPAN.RAW.MIMECAST_PROCESS_LOGS
Limit 10

-- Selects the first 10 rows from the MIMECAST_RECEIPT_LOGS table in the SECNNET_ASIA_JAPAN.RAW schema
SELECT *
FROM SECNNET_ASIA_JAPAN.RAW.MIMECAST_RECEIPT_LOGS
Limit 10

-- Selects the first 10 rows from the MIMECAST_SPAM_EVENT_THREAD_LOGS table in the SECNNET_ASIA_JAPAN.RAW schema
SELECT *
FROM SECNNET_ASIA_JAPAN.RAW.MIMECAST_SPAM_EVENT_THREAD_LOGS
Limit 10

-- Selects the first 10 rows from the MIMECAST_URL_PROTECT_LOGS table in the SECNNET_ASIA_JAPAN.RAW schema
SELECT *
FROM SECNNET_ASIA_JAPAN.RAW.MIMECAST_URL_PROTECT_LOGS
Limit 10

---------------------------------------------------------------------------------------------------------



