--This is a series of five SQL queries that are selecting data from different tables in the SECNNET_ASIA_JAPAN database schema. The queries are retrieving the first 10 rows of data from each of the tables named in the query.

--The tables in question appear to relate to data generated by various Symantec endpoint protection products, such as DLP (Data Loss Prevention), IDS (Intrusion Detection System), risk events, and scans. The specific data being retrieved is not indicated in the queries, as the '*' symbol is used to select all columns in each table.

--Overall, the purpose of these queries is to retrieve a small subset of data from the specified tables for analysis or review, possibly as part of a larger data analytics or security investigation effort.

SELECT *
FROM SECNNET_ASIA_JAPAN.RAW.SYMANTEC_DLP_LOGS
Limit 10

SELECT *
FROM SECNNET_ASIA_JAPAN.RAW.SYMANTEC_ENDPOINT_PROTECTION_IDS_EVENTS
Limit 10

SELECT *
FROM SECNNET_ASIA_JAPAN.RAW.SYMANTEC_ENDPOINT_PROTECTION_RISK_EVENTS
Limit 10

SELECT *
FROM SECNNET_ASIA_JAPAN.RAW.SYMANTEC_ENDPOINT_PROTECTION_SCANS
Limit 10

SELECT *
FROM SECNNET_ASIA_JAPAN.RAW.SYMANTEC_ENDPOINT_PROTECTION_SONAR_RAW
Limit 10
